### ISSUE TITLE
Anchored or moored targets

### ISSUE THREAD

**Issue by transmitterdan** [Verezano/AISradar_pi#12]
A user requested the feature of a black dot on targets that have anchored or moored status. I have done this and it is tested. Would it be best to make a new version number or just add this feature to the existing master branch? Or do you not care to implement this feature?

**Comment by Verezano** [comment]
Hi Dan,

If that improves the plug-in I'm happy to add it.

Regards
Johan

Op 23 sep. 2017 23:41 schreef "transmitterdan" <notifications@github.com>:

**Comment by Verezano** [comment]
Hi Dan,

The repository  has been renamed to AISradar_pi as r Gleason suggested. I also removed most references to radar as it is not a radar plugin. It is tagged as aisradar_piv1.2. In 2011 when it was created I never guessed ocpn would get where it is now.
Any enhancements are welcome

Regards
Johan
