### ISSUE TITLE
Plugin Manager - Frontend2

### ISSUE THREAD

**Issue by rgleason** [Verezano/AISradar_pi#14]
Jordan,
Would you like me to fork and make a PR that adds Plugin Manager Frontend2 that will bring your Plugin into the current way of installing?  I would then make a Pull Request to your repos.

PS: it becomes availabe to a number of environments.

**Comment by Verezano** [comment]
Hi Rick,

Yes please. Your help is much appreciated.

Regards
Johan

Op zo 12 jul. 2020 23:22 schreef Rick Gleason <notifications@github.com>:
