### ISSUE TITLE
 AISradar range is not working. We have had to remove this update from the PI Catalogs.

### ISSUE THREAD

**Issue by rgleason** [Verezano/AISradar_pi#28]
Hannes,

Note: I tried merging a small change in Verezano repo made awhile ago. The plugin is still misbehaving and not working, but please[ accept the PR ](https://github.com/Verezano/AISradar_pi/pulls)and then fix the range problems.

Please see this issue  Opencpn 5.7.1  AISradar problem.
https://github.com/rgleason/AISradar_pi/issues/14

I have been unable to find where this is being calculated for each Target.
Can you advise? 

Also why would it be calculating approximately 2nm for all Targets?
I can set breakpoints and step through things, but have not been able to find the lines where this is calculated and need your help to fix this problem.

Thanks. Rick

**Comment by Verezano** [comment]
Hi Rick,

Thats odd. I'll dig into it.
Keep you posted

Johan

Op za 7 jan. 2023 14:23 schreef Rick Gleason ***@***.***>:

**Comment by rgleason** [comment]
Johan, Thanks very much. It would be nice to be able to push this to the master catalog.
I include a link to the current manual https://opencpn-manuals.github.io/main/aisradar/index.html

I didn't write it but under "[Remarks"](https://opencpn-manuals.github.io/main/aisradar/index.html#_remarks) there is some discussion about "disadvantages
I wonder if there are some things that could be done to improve this?

**Comment by rgleason** [comment]
Johan,
Can you solve this problem?  I would like to update your plugin for version O5.8 and push it to master catalog, but as it is working now it will not be at all useful.
https://github.com/rgleason/AISradar_pi/issues/14

I tried to compare your master branch to mine and found a few differences, if you look here you will see them
https://github.com/rgleason/AISradar_pi/pull/15/files

What do you think these changes would do?

Thanks.
Rick

**Comment by rgleason** [comment]
Removed from PIM master and Beta Catalogs until these problems are fixed.
